"""empty message

Revision ID: 2999eae9482a
Revises: None
Create Date: 2014-09-09 12:32:42.782000

"""

# revision identifiers, used by Alembic.
revision = '2999eae9482a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('term', sa.String(length=255), nullable=True),
    sa.Column('reward', sa.String(length=255), nullable=True),
    sa.Column('img_upload', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advert')
    ### end Alembic commands ###
